### ISSUE TITLE
Nothing working except "Live" option

### ISSUE THREAD

**Issue by jamazerto** [AddonScriptorDE/plugin.video.arte_tv#6]
Since a few days ago, reading videos has become impossible ("script error" message appears every time we try). Only the live option works.
Also when looking at the programs "by date" nothing is found.
I tried with the sciprt v 2.1.1 and 2.0.5 same result.
Running xbmc 13.2 on raspbmc.
here's the log:
Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.video.arte_tv/default.py", line 342, in <module>
                                                playVideoNew(url)
                                              File "/home/pi/.xbmc/addons/plugin.video.arte_tv/default.py", line 213, in playVideoNew
                                                listitem = xbmcgui.ListItem(path=getStreamUrlNew(url))
                                              File "/home/pi/.xbmc/addons/plugin.video.arte_tv/default.py", line 220, in getStreamUrlNew
                                                url = match[0].replace("/player/","/")
                                            IndexError: list index out of range

**Comment by esieke** [comment]
I also had an issue and this patch has solved it:
https://github.com/AddonScriptorDE/plugin.video.arte_tv/pull/3/files

see also:
http://forum.xbmc.org/showthread.php?tid=132563&page=11
Post: 156

Thanks alot for the patch

**Comment by jamazerto** [comment]
Thanks, this change did help: I can now read videos again. However there are still nothing in the "by date" section.

**Comment by AlexandreHagen** [comment]
Hi 
Same thing to me, there are nothing in "by date".

**Comment by jbudziak** [comment]
Thanks :)

**Comment by felgru** [comment]
Take a look at pull request #8 (especially commit 05ab260f012b77bf2463c6d170f427338f39019e), that should fix the empty "by date" section.
